swagger: "2.0"
info:
  version: "1.0.0"
  title: "ranking-api"
  description: "Endpois para visualizar rankins nacionais e internacionais"
  contact:
    name: "Conecta Amazonia"
    email: "bergson.silva.rodrigues@gmail.com"
basePath: "/api"
paths:
  "/entities/{idEntidade}":
    get:
      parameters:
        - name: idEntidade
          in: path
          required: true
          description: "Id da entidade"
          type: "string"
      tags:
        - "organizational-structure"
      summary: "Consulta os detalhes de uma entidade no estrutura organizacional"
      operationId: "handlerOrganizationalStructure"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Entidade"
        500:
          description: "Erro ao executar operação"

  "/cooperativas/{uidUsuario}":
    get:
      parameters:
        - name: uidUsuario
          in: path
          required: true
          description: "Id do usuário"
          type: "string"
      tags:
        - "cooperativas"
      summary: "Consulta as cooperativas de um usuário na estrutura organizacional"
      operationId: "buscarCooperativas"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            type: "object"
            properties:
              content:
                type: "array"
                items:
                  $ref: "#/definitions/Cooperativa"
              size:
                type: "integer"
        500:
          description: "Erro ao executar operação"
  "/pessoas":
    get:
      parameters:
        - name: oidPessoa
          in: query
          required: true
          description: "Id(s) de pessoa(s)"
          type: array
          items: 
            type: integer
          collectionFormat: multi
      tags:
        - "pessoas"
      summary: "Consulta de pessoas por id no sistema de cadastro"
      operationId: "getPessoas"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pessoa"
        500:
          description: "Erro ao executar operação"
  "/pessoas/pesquisa":
    get:
      parameters:
        - name: agencia
          in: query
          description: "Agência da pessoa"
          type: "string"
        - name: documento
          in: query
          description: "CPF ou CNPJ da pessoa (apenas números)"
          type: "string"
        - name: tipo
          in: query
          description: "Tipo de pessoa, física ou jurídica"
          type: string
          enum: [PF, PJ]
      tags:
        - "pessoas"
      summary: "Consulta uma pessoa por agência, documento e tipo no sistema de cadastro"
      operationId: "findPessoas"
      consumes:
        - "application/json"
      produces:
      - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Pessoa"
        500:
          description: "Erro ao executar operação"
  "/pessoas/endereco/{codigoCooperativa}/{documento}":
    get:
      parameters:
        - name: codigoCooperativa
          in: path
          required: true
          description: "Código da cooperativa"
          type: "string"
        - name: documento
          in: path
          required: true
          description: "Documento do pessoa"
          type: "string"          
      tags:
        - "pessoas"
      summary: "Consulta o endereço da pessoa no sistema de cadastro"
      operationId: "consultarEndereco"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Endereco"
        404:
          description: "Endereço não encontrado"
        500:
          description: "Erro ao executar operação"          
  "/boletos/pagador/{codigoCooperativa}/{cnpj}":
    get:
      parameters:
        - name: codigoCooperativa
          in: path
          required: true
          description: "Código da cooperativa"
          type: "string"
        - name: cnpj
          in: path
          required: true
          description: "CNPJ do pagador"
          type: "string"          
      tags:
        - "boletos"
      summary: "Consulta o código do pagador no sistema de cobrança"
      operationId: "consultarPagador"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Pagador"
        404:
          description: "Pagador não encontrado"
        500:
          description: "Erro ao executar operação"
  "/boletos/pagador":
    post:
      parameters:
        - name: body
          in: body
          required: true
          description: "Dados necessários para cadastro do pagador no sistema de cobrança"
          schema:
            $ref: "#/definitions/CadastroPagador"
      tags:
        - "boletos"
      summary: "Cadastra um pagador no sistema de cobrança"
      operationId: "cadastrarPagador"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Pagador"
        500:
          description: "Erro ao executar operação"           
  "/boletos/vencimento/{diaVencimento}/{competencia}":
    get:
      parameters:
        - name: diaVencimento
          in: path
          required: true
          description: "Dia de vencimento das parcelas"
          type: "integer"
        - name: competencia
          in: path
          required: true
          description: "Competência do repasse"
          type: "string"
      tags:
        - "boletos"
      summary: "Consulta o vencimento para inclusão do boleto"
      operationId: "consultarVencimento"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/VencimentoBoleto"
        404:
          description: "Vencimento não encontrado"
        500:
          description: "Erro ao executar operação"             
  "/boletos":
    post:
      parameters:
        - name: body
          in: body
          required: true
          description: "Dados necessários para cadastro do boleto no sistema de cobrança"
          schema:
            $ref: "#/definitions/CadastroBoleto"
      tags:
        - "boletos"
      summary: "Cadastra um boleto no sistema de cobrança"
      operationId: "cadastrarBoleto"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/CadastroBoleto"
        500:
          description: "Erro ao executar operação" 
  "/boletos/arquivo/{nossoNumero}/{codigoCedente}/{codigoAgencia}":
    get:
      parameters:
        - name: nossoNumero
          in: path
          required: true
          description: "Nosso número"
          type: "string"
        - name: codigoCedente
          in: path
          required: true
          description: "Código do cedente"
          type: "string"
        - name: codigoAgencia
          in: path
          required: true
          description: "Código da agência"
          type: "string"    
      tags:
        - "boletos"
      summary: "Consulta o arquivo gerado no sistema de cobrança"
      operationId: "consultarArquivo"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/ArquivoBoleto"
        404:
          description: "Arquivo não encontrado"
        500:
          description: "Erro ao executar operação"
  "/cadastro/dias-uteis":
    get:
      parameters:
        - name: data
          in: query
          description: "data a ser pesquisada"
          type: "string"
      tags:
        - "cadastro"
      summary: "Verifica se a data é util no sistema de cadastro"
      operationId: "testarDiasUteis"
      consumes:
        - "application/text"
      produces:
      - "application/tex"
      security:
        - Bearer: []
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            type: string
            example: true 
        500:
          description: "Erro ao executar operação"
  
definitions:
  Cooperativa:
    properties:
      oidCooperativa:
        type: "integer"
        format: "int64"
      codCooperativa:
        type: "string"
      nomCooperativa:
        type: "string"
  Pessoa:
    properties:
      oidPessoa:
        type: "integer"
        format: "int64"
      numDocumento:
        type: "string"
      nomPessoa:
        type: "string"
      tpoPessoa:
        type: "string"
  Pagador:
    properties:
      codigo:
        type: "string"
  CadastroPagador:
    properties:
      razaoSocial:
        type: "string" 
      cnpj:
        type: "string"         
      endereco:
        $ref: "#/definitions/Endereco"                  
      codigoCooperativa:
        type: "string"       
      codigoCedente:
        type: "string"                        
  Endereco:
    properties:
      nomeLogradouro:
        type: "string" 
      tipoLogradouro:
        type: "string"         
      numero:
        type: "string"         
      complemento:
        type: "string"     
      bairro:
        type: "string"                             
      nomeCidade:
        type: "string"                        
      siglaUf:
        type: "string"       
      cep:
        type: "string"                                
  VencimentoBoleto:
    properties:
      dataVencimento:
        type: "string"
        format: "date"        
  CadastroBoleto:
    properties:
      codigoCooperativa:
        type: "string"                        
      codigoCedente:
        type: "string"       
      codigoPagador:
        type: "string"                       
      dataVencimento:
        type: "string"
        format: "date"
      seuNumero:
        type: "string"
      valorPrincipal:
        type: "number"
  Boleto:
    properties:
      nossoNumero:
        type: "string"
      cooperativaDestino:
        type: "string"        
  ArquivoBoleto:
    properties:
      arquivo:
        type: "string"                        
        format: "base64"
  Entidade:
    properties:
      denominacaoSocial:
        type: "string"
